[package]
name = "pluto-macros"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
syn = "1.0.95"
quote = "1.0.18"
proc-macro2 = "1.0.39"
regex = "1.5.6"
lazy_static = "1.4.0"
